'use strict';

const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-express-generator');

const options = {
  swaggerDefinition: {
    info: {
      title: 'api-server',
      version: '0.0.1',
      description: 'Express API server with autogenerated Swagger documentation via swagger-jsdoc',
    },
    host: 'localhost:8080',
  },
  apis: ['./*.js'],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = (app) => {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
};